<?PHP
echo 'Learn the ins and outs of Linux while playing a game!';
echo date('M').' '.date('d').' '.date('Y');

echo '<table border=2 width="100%">';
    echo '<tr>';
        echo '<td width="200px">';
            echo '[review] [game]';
        echo '</td>';
        echo '<td>';
        echo '</td>';
        echo '<td width="200px">';
            echo '[Login] [User] [*Pass]';
        echo '</td>';
    echo '</tr>';
        echo '<tr height="90px">';
            echo '<td>';
            echo '</td>';
            echo '<td>';
                echo '[highscores]';
            echo '</td>';
            echo '<td >';
            echo '</td>';
    echo '</tr>';
    echo '</tr>';
        echo '<tr height="90px">';
            echo '<td>';
            echo '</td>';
            echo '<td>';
                require('./ads/LGUnderHS.php');
                #echo '[ad]';
            echo '</td>';
            echo '<td >';
            echo '</td>';
    echo '</tr>';
    echo '</tr>';
        echo '<tr height="600px">';
            echo '<td>';
            echo '</td>';
            echo '<td>';
                echo '[game]';
            echo '</td>';
            echo '<td >';
                require('./ads/LGRightBar.php');
                #echo '[ad]';            
            echo '</td>';
    echo '</tr>';
    echo '</tr>';
        echo '<tr height="90px">';
            echo '<td>';
            echo '</td>';
            echo '<td>';
                require('./ads/LGUnderGame.php');
                #echo '[ad]';
            echo '</td>';
            echo '<td >';
            echo '</td>';
    echo '</tr>';    
?>